name: Send submodule updates to parent repo

on:
  push:
    branches: 
      - master
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"
  
permissions: write-all

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
        with: 
          submodules: true
          fetch-depth: 1

      - name: Pull & update submodules recursively
        run: |
          # git submodule update --init --remote
          git submodule init
          git submodule sync
          git submodule foreach git fetch -v --depth=1
          SM=`git submodule | cut -c2- | cut -d' ' -f2`
          for f in $SM
          do
            echo $f
            git submodule update --remote ${f} || echo "CHYBA"
          done


      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
